#cloud-config
ssh_pwauth: false
packages:
  - fail2ban
  - git
  - ufw
  - vim
package_update: true
package_upgrade: true
write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 1w
      findtime = 1d
      maxretry = 2
runcmd:
  - ufw allow 22/tcp
  - ufw allow 443/tcp
  - ufw enable
  - reboot
